server:
  servlet:
    context-path: /eblog
  port: 8088

spring:
  # 数据源配置
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # Mybatis-Plus SQL分析器
    url: jdbc:p6spy:mysql://106.55.0.87:3306/eblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: swwljy

  # 模板配置
  freemarker:
    settings:
      classic_compatible: true   # 处理空值
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##

  # Redis配置
  redis:
    host: 106.55.0.87
    port: 6379
    password:

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
